derrida/books/urls.py
from django.conf.urls import url, include
from django.contrib.admin.views.decorators import staff_member_required

from derrida.books import views


app_name = 'derrida.books'

urlpatterns = [
    url(r'^publishers/autocomplete/$', staff_member_required(views.PublisherAutocomplete.as_view()),
        name='publisher-autocomplete'),
    url(r'^languages/autocomplete/$', staff_member_required(views.LanguageAutocomplete.as_view()),
        name='language-autocomplete'),

    # cross-item search
    url(r'^search/$', views.SearchView.as_view(), name='search'),

    # reference views
    url(r'^references/', include([
        url(r'^$', views.ReferenceListView.as_view(), name='reference-list'),
        url(r'^histogram/$', views.ReferenceHistogramView.as_view(),
            name='reference-histogram'),
        url(r'^histogram/(?P<derridawork_slug>[a-z-\d]+)/$',
            views.ReferenceHistogramView.as_view(), {'mode': 'section'},
            name='reference-histogram'),
        url(r'^(?P<derridawork_slug>[a-z-]+)/(?P<page>[\dA-Z]+)(?P<pageloc>[a-z]+)?/$',
            views.ReferenceDetailView.as_view(), name='reference'),
    ])),

    # library views
    url(r'^library/', include([
        url(r'^$', views.InstanceListView.as_view(), name='list'),
        url(r'^(?P<slug>[-\w]+)/', include([
            url(r'^$', views.InstanceDetailView.as_view(), name='detail'),
            url(r'^references/$',
                views.InstanceReferenceDetailView.as_view(), name='detail-references'),
            url(r'^gallery/$',
                views.InstanceDetailView.as_view(template_name='books/detail/gallery.html'),
                name='detail-gallery'),
            url(r'^gallery/(?P<short_id>[a-z0-9-]+)/$',
                views.CanvasDetail.as_view(), name='canvas-detail'),
            url(r'^suppress-images/$', views.CanvasSuppress.as_view(), name='suppress-canvas'),
            # canvas image views
            url(r'^gallery/images/(?P<page_num>[0-9vix]{1,4})-?[0-9]*[a-z]?(?P<x>@2x)?/$',
                views.CanvasImageByPageNumber.as_view(), {'mode': 'by-page'}, name='canvas-by-page'),
            url(r'^gallery/images/(?P<short_id>[a-z0-9-]+|default)/(?P<mode>smthumb|thumbnail|large|info)(?P<x>@2x)?/$',
                views.CanvasImage.as_view(), name='canvas-image'),
            url(r'^gallery/images/(?P<short_id>[a-z0-9-]+)/(?P<mode>iiif)(?P<url>.*)$',
                views.CanvasImage.as_view(), name='canvas-iiif'),

            # default thumbnail for a book
            url(r'^(?P<mode>smthumb|thumbnail)(?P<x>@2x)?/$',
                views.CanvasImage.as_view(), name='book-image')
        ])) # end library/<slug> urls
    ])), # end library urls

    url(r'^titles/(?P<pk>\d+)/', views.InstanceURIView.as_view(), name='instance'),

]

derrida/urls.py
"""derrida URL Configuration
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
"""
from annotator_store import views as annotator_views
# from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps import views as sitemap_views
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
import mezzanine.urls
import mezzanine.pages.views

from derrida.books.views import SearchView
from derrida.books import sitemaps as book_sitemaps
from derrida.outwork import sitemaps as page_sitemaps


sitemaps = {
    'pages': page_sitemaps.PageSitemap,
    'books': book_sitemaps.InstanceSitemap,
    'book-references': book_sitemaps.InstanceReferencesSitemap,
    'book-gallery': book_sitemaps.InstanceGallerySitemap,
    'book-pages': book_sitemaps.CanvasSitemap,
}


urlpatterns = [
    # direct 500 access for testing and web scraping
    url(r"^_500/", lambda _: 1 / 0),

    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt',
        content_type='text/plain')),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico',
        permanent=True)),
    url(r'^sitemap\.xml$', sitemap_views.index, {'sitemaps': sitemaps},
        name='sitemap-index'),
    url(r'^sitemap-(?P<section>.+)\.xml$',
        sitemap_views.sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),

    # home page managed via mezzanine, but needs a named url
    url(r'^$', mezzanine.pages.views.page, {"slug": "/"}, name="home"),
    # alternate homepage named url needed for djiffy templates
    url(r'^$', mezzanine.pages.views.page, {"slug": "/"}, name="site-index"),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('pucas.cas_urls')),
    url(r'^', include('derrida.books.urls', namespace='books')),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^people/', include('derrida.people.urls', namespace='people')),
    url(r'^places/', include('derrida.places.urls', namespace='places')),
    url(r'^interventions/', include('derrida.interventions.urls',
        namespace='interventions')),
    url(r'^viaf/', include(('viapy.urls', 'viapy'), namespace='viaf')),
    url(r'^outwork/', include('derrida.outwork.urls', namespace='outwork')),

    # local version of djiffy urls
    url(r'^admin/iiif-books/',
        include(('derrida.interventions.iiif_urls', 'djiffy'),
                namespace='djiffy')),

    # annotations API
    url(r'^annotations/api/', include('annotator_store.urls',
        namespace='annotation-api')),
    # annotatorjs doesn't handle trailing slash in api prefix url
    url(r'^annotations/api', annotator_views.AnnotationIndex.as_view(),
        name='annotation-api-prefix'),

    # content pages managed by mezzanine
    url("^", include(mezzanine.urls)),
]


# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

derrida/interventions/models.py
from attrdict import AttrDict
from annotator_store.models import BaseAnnotation, AnnotationQuerySet
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.urls import reverse
from djiffy.models import Canvas

from derrida.books.models import Language
from derrida.common.models import Named, Notable
from derrida.common.utils import absolutize_url
from derrida.people.models import Person


#: intervention type codes to distinguish annotations and insertions
INTERVENTION_TYPES = AttrDict({
    'ANNOTATION': 'A',
    'INSERTION': 'I',
    'BOTH': 'AI',
})


def get_default_intervener():
    """Function to either return the pk of a :class:`~derrida.people.models.Person`
    object representing Jacques Derrida if he exists in the database or None"""
    try:
        return (Person.objects.get(authorized_name='Derrida, Jacques')).pk
    except ObjectDoesNotExist:
        return None


class TagQuerySet(models.QuerySet):
    '''Custom :class:`~django.db.models.QuerySet` for :class:`Tag` to
    make it easy to find tags that apply to a particular kind of
    Intervention.'''

    def for_annotations(self):
        '''Find tags that apply to annotations'''
        return self.filter(applies_to__contains=INTERVENTION_TYPES.ANNOTATION)

    def for_insertions(self):
        '''Find tags that apply to insertions'''
        return self.filter(applies_to__contains=INTERVENTION_TYPES.INSERTION)


class Tag(Named, Notable):
    APPLIES_TO_CHOICES = (
        (INTERVENTION_TYPES.ANNOTATION, 'Annotations only'),
        (INTERVENTION_TYPES.INSERTION, 'Insertions only'),
        (INTERVENTION_TYPES.BOTH, 'Both Annotations and Insertions'),
    )
    applies_to = models.CharField(max_length=2, choices=APPLIES_TO_CHOICES,
        default=INTERVENTION_TYPES.BOTH,
        help_text='Type or types of interventions this tag is applicable to.')

    objects = TagQuerySet.as_manager()


class InterventionQuerySet(AnnotationQuerySet):

    def sorted_by_page_loc(self):
        '''
        Return a list of :class:`~derrida.interventions.models.Intervention`
        objects sorted by their y value on the page.
        '''
        def sort_y(item):
            # assume zero if not present
            y_percent = item.extra_data.get('image_selection', {}).get('y', '0').strip('%')
            return float(y_percent)
        # return sorted list of current queryset based on y coord image selection
        return sorted(self, key=sort_y)


class Intervention(BaseAnnotation):

    INTERVENTION_TYPE_CHOICES = (
        (INTERVENTION_TYPES.ANNOTATION, 'Annotation'),
        (INTERVENTION_TYPES.INSERTION, 'Insertion'),
    )
    intervention_type = models.CharField(
        max_length=2,
        choices=INTERVENTION_TYPE_CHOICES,
        default=INTERVENTION_TYPES.ANNOTATION,
    )

    #: associated IIIF :class:`djiffy.models.Canvas` for interventions
    #: related to an image
    canvas = models.ForeignKey(Canvas, null=True, blank=True)
    #: Tags to describe the intervention and its characteristics;
    #: many-to-many relationship to :class:`Tag`
    tags = models.ManyToManyField(Tag, blank=True,
        help_text='Tags to describe this intervation and its characteristics')
    #: language of the intervention text (i.e. :attr:`text`)
    text_language = models.ForeignKey(Language, null=True, blank=True,
        help_text='Language of the intervention text', related_name='+')
    #: translation language of the intervention text (i.e. :attr:`text`)
    text_translation = models.TextField(blank=True,
        help_text='Translation of the intervention text (optional)')

    #: language of the quoted text or anchor text (i.e. :attr:`quote`)
    quote_language = models.ForeignKey(Language, null=True, blank=True,
            help_text='Language of the anchor text', related_name='+')
    #: Associated author, instance of :class:`~derrida.people.models.Person`
    author = models.ForeignKey(Person, null=True, blank=True,
        default=get_default_intervener)

    objects = InterventionQuerySet.as_manager()

    def __str__(self):
        """Override str to make sure that something is displayed
        for Django admin and autocompletes"""
        if not self.quote and not self.text:
            string = '%s with no text' % self.get_intervention_type_display()
            if self.tags.all():
                tag_names = ', '.join(
                    sorted([tag.name for tag in self.tags.all()])
                )
                string = '%s, tagged as %s' % (string, tag_names)
        # Organize so that self.quote is set if it exists
        if self.text:
            string = self.text
        if self.quote:
            string = self.quote
        # If there's an associated canvas, supply that
        if self.canvas:
            string = '%s (%s)' % (string, self.canvas.label)
        return string

    class Meta:
        # extend default permissions to add a view option
        # change_annotation and delete_annotation provided by django
        permissions = (
            ('view_intervention', 'View intervention'),
        )

    def save(self, *args, **kwargs):
        # for image annotation, URI should be set to canvas URI; look up
        # canvas by URI and associate with the record

        # if canvas is already set and uri matches annotation uri, do nothing
        if self.canvas and self.uri == self.canvas.uri:
            pass
        else:
            # otherwise, lookup canvas and associate
            # (clear out in case there is no match for the new uri)
            self.canvas = None
            try:
                self.canvas = Canvas.objects.get(uri=self.uri)
            except Canvas.DoesNotExist:
                pass
        super(Intervention, self).save()

    def get_uri(self):
        '''Return a public URI for this intervention that can be used as an identifier'''
        return absolutize_url(reverse('interventions:view', args=[self.id]))

    def is_verbal(self):
        '''Return whether a :class:`Intervention` has a verbal component.'''
        return bool(self.text)
    # Sorts on the binary of whether an intervention does or does not
    # have text
    is_verbal.boolean = True
    is_verbal.admin_order_field = 'text'

    def is_annotation(self):
        '''Return whether :class:`Intervention` object is an annotation.'''
        return self.intervention_type == INTERVENTION_TYPES.ANNOTATION

    def is_insertion(self):
        '''Return whether :class:`Intervention` object is an insersetion.'''
        return self.intervention_type == INTERVENTION_TYPES.INSERTION

    @property
    def digital_edition(self):
        '''digital edition this annotation is associated, via
        :class:`djiffy.models.Canvas`'''
        return self.canvas.manifest

    @property
    def work_instance(self):
        '''Annotated library work :class:`derrida.books.models.Instance`,
        via associated :attr:`digital_edition`.'''
        if self.canvas:
            return self.canvas.manifest.instance

    @property
    def annotation_type(self):
        '''List of annotation types. Generated from tags, excluding ink
        and pencil tags, uncertain and illegible tags, and with the
        addition of verbal or nonverbal  annotation.'''
        # tags from being treated as annotation types?
        tags = [tag.name for tag in self.tags.all() if not any(
                ['ink' in tag.name, 'pencil' in tag.name,
                 'uncertain' in tag.name, 'illegible' in tag.name])]
        if self.is_verbal():
            tags.append('verbal annotation')
        else:
            tags.append('nonverbal annotation')
        return tags

    @property
    def ink(self):
        '''pen ink color or pencil, from tags'''
        return [tag.name for tag in self.tags.all() if any(
                ['ink' in tag.name, 'pencil' in tag.name])]

    # NOTE: iiif_image_selection and admin_thumbnail borrowed
    # directly from cdh winthrop annotation code

    img_info_to_iiif = {'w': 'width', 'h': 'height', 'x': 'x', 'y': 'y'}

    def iiif_image_selection(self):
        '''
        Generate a IIIF image selection for a :class:`Intervention` if it
        image selection information is present and a canvas is associated.
        '''
        # if image selection information is present in annotation
        # and canvas is associated, generated a IIIF image for the
        # selected portion of the canvas
        if 'image_selection' in self.extra_data and self.canvas:
            # convert stored image info into the format used by
            # piffle for generating iiif image region
            img_selection = {
                self.img_info_to_iiif[key]: float(val.rstrip('%'))
                for key, val in self.extra_data['image_selection'].items()
                if key in self.img_info_to_iiif
            }
            return self.canvas.image.region(percent=True, **img_selection)

    def admin_thumbnail(self):
        '''
        Provide an admin thumbnail image of associated IIIF image selection.
        '''
        img_selection = self.iiif_image_selection()
        # if image selection is available, display small thumbnail
        if img_selection:
            return u'<img src="%s" />' % img_selection.mini_thumbnail()
        # otherwise, if canvas is set, display canvas small thumbnail
        if self.canvas:
            return u'<img src="%s" />' % self.canvas.image.mini_thumbnail()
    admin_thumbnail.short_description = 'Thumbnail'
    admin_thumbnail.allow_tags = True

    def handle_extra_data(self, data, request):
        '''Handle "extra" data that is not part of the stock annotation
        data model.  Used to support custom fields that are
        specific to :class:`Intervention`.  Data is as provided from json
        request data, as sent by annotator.js.'''

        # If the object does not yet exist in the database, it must be

derrida/books/templates/books/canvas_detail.html
{% extends 'djiffy/base.html' %}
{% load static %}

{% block page-subtitle %}{{ instance.work.primary_title }}{% if instance.work.authors.count == 1 %}, {{ instance.work.authors.first.lastname }}{% endif %} {% if instance.print_year or instance.copyright_year %}({% firstof instance.print_year instance.copyright_year %}{% if instance.copy %} - {{ instance.copy }}{% endif %}){% endif %} ‖ {% endblock %}
{% block nav-title %} Derrida's Library {% endblock %}

{% block header_class %}mdl-layout__header--transparent{% endblock %}

{% block page-context-id %}books-detail{% endblock %}

{% block content %}
  <header class="page-header page-header--link">
    <div class="container">
      <h1 class="page-header__heading"><a href="{% url 'books:detail-gallery' instance.slug %}"><span class="arrow_icon">←</span> Book Image Gallery</a></h1>
    </div>
  </header>
  <article class="item">
    <div class="container">

        {# brief title information (copied from book-header) #}
        {% with book=instance %}
        <h1 class="item-title">{{ book.work.primary_title }}</h1>
        <p class="item-author">
          {% for author in book.work.authors.all %}
            {% if not forloop.last %}
              {{ author.authorized_name }};
            {% else %}
              {{ author.authorized_name }}
            {% endif %}
          {% endfor %}
        </p>
        <p class="item-term__value">{{ book.copyright_year }}{% if book.copy %} - {{ book.copy }}{% endif %}</p>
        {% endwith %}

        {# locations where cited by Derrida #}
        {% if instance.reference_set.all %}
        Cited in <em>{{ instance.reference_set.all.0.derridawork }}</em>
        <ul>
        {% for reference in instance.reference_set.all %}
            <li>p.{{ reference.derridawork_page }} {{ reference.derridawork_pageloc }}</li>
        {% endfor %}
        </ul>
        {% endif %}

      {# pages in this volume - navigation list #}

      {# overview images #}
      {% if instance.overview_images %}
      <h3>Overview Images</h3>
      <ul>
      {% for canvas in instance.overview_images %}
          <li><a href="{% url 'books:canvas-detail' instance.slug canvas.short_id %}">
              {{ canvas.label }}</a></li>
      {% endfor %}
      </ul>
      {% endif %}

      {% if instance.annotated_pages %}
      <h3>Annotated pages</h3>
      <ul>
     {% for canvas in instance.annotated_pages %}
          <li><a href="{% url 'books:canvas-detail' instance.slug canvas.short_id %}">
              {{ canvas.label }}</a></li>
      {% endfor %}
      </ul>
      {% endif %}

       {% if instance.insertion_images %}
       <h3>Insertions</h3>
       <ul>
       {% for canvas in instance.insertion_images %}
          <li><a href="{% url 'books:canvas-detail' instance.slug canvas.short_id %}">
              {{ canvas.label }}</a></li>
      {% endfor %}
      </ul>
      {% endif %}

      {# large size image #}
      <img class="img" src="{% url 'books:canvas-image' instance.slug canvas.short_id 'large' %}" />


      {# TODO: deep zoom #}

      {# image selection zones  #}
       {# {% for intervention in canvas.intervention_set.all %} #}
       {# provides x,y offset and width,height in percentages #}
       {# {{ intervention.extra_data.image_selection }} #}
       {# {% endfor %} #}

        <article class="collection">
       {% for intervention in canvas.intervention_set.all %}
            {% include 'components/intervention-card.html' %}
       {% endfor %}
    </article>

<div id="deep-zoom" style="width: 800px; height: 600px;"></div>
<script src="{% static 'js//openseadragon/openseadragon.min.js' %}"></script>
<script type="text/javascript" charset="utf-8">
   $(document).ready(function () {
      // seadragon configuration  for deep zoom
        var viewer = OpenSeadragon({
          id: "deep-zoom",
          prefixUrl: "{% static 'js/openseadragon/images/' %}",
          tileSources: "{% url 'books:canvas-image' instance.slug canvas.short_id 'info' %}",
      });
    });
</script>

    </div>
  </article>
{% endblock %}

derrida/books/templates/books/instance_detail.html
{% extends 'base.html' %}
{% load static %}

{% block page-subtitle %}{{ instance.work.primary_title }}{% if instance.work.authors.count == 1 %}, {{ instance.work.authors.first.lastname }}{% endif %} {% if instance.print_year or instance.copyright_year %}({% firstof instance.print_year instance.copyright_year %}{% if instance.copy %} - {{ instance.copy }}{% endif %}){% endif %} ‖ {% endblock %}
{% block nav-title %} Derrida's Library {% endblock %}

{% block header_class %}mdl-layout__header--transparent{% endblock %}

{% block page-context-id %}books-detail{% endblock %}

{% block content %}
  <header class="page-header page-header--link">
    <div class="container">
      <h1 class="page-header__heading"><a class="page-header__link" href="{% url 'books:list' %}"><span class="arrow_icon">⟵</span> Derrida's Library</a></h1>
    </div>
  </header>
  <article class="item">
    <div class="container">
      {% include 'components/book-details.html' with book=instance %}
    </div>
  </article>
{% endblock %}

derrida/books/templates/books/instance_list.html
{% extends 'base.html' %}
{% load static %}

{% block page-subtitle %}{{ page.meta_title }} ‖ {% endblock %}
{% block nav-title %} {{ page.title }} {% endblock %}

{% block preview_meta %}
{# override preview image #}
{% with page_meta_image='img/banner/derrida-banner-library-S@2x.png' twitter_card='summary_large_image' %}
    {{ block.super }}
{% endwith %}
{% endblock %}

{% block header_class %}mdl-layout__header--transparent{% endblock %}

{% block page-context-id %}books-list{% endblock %}

{% block content %}
  <header class="page-header header-banner">
    <div class="container page-header__container">
      <h1 class="page-header__heading">{{ page.title }}</h1>
      <div class="page-header__callout">
        <p class="lead">{{ page.description }}</p>
        {# <p class="help">Only books extant in the Library of Jacques Derrida collection, held at the Princeton University Library’s Department of Rare Books and Special Collections, are displayed below.</p> #}
        <p><a class="callout__link" href="{% url 'books:reference-list' %}">A full list of references is accessible through Reference List.</a> <a class="callout__link" href="https://www.zotero.org/groups/2237221/derridas_margins">View all cited works as a Zotero library</a> or
      <a class="callout__link" href="https://doi.org/10.34770/2ezk-1104">download data for all cited works.</a></p>
      </div>
    </div>
  </header>

  {% include "components/page-filter.html" with formItems=form %}
  {% include "components/page-sort.html" with number=count orderBy=orderBy %}

  <div class="container">
    <div class="loading-spinner">
      <img src="{% static 'img/loading.gif' %}" alt="↻"/>
    </div>
    <article class="collection collection--condensed">
      {% for instance in object_list %}
        {% url 'books:detail' instance.slug as instance_url %}
        {% include 'components/books-list-item.html' with href=instance_url book=instance thumbnail_size='thumbnail' %}
      {% empty %}
        {% include 'components/search-results-empty.html' %}
      {% endfor %}
    </article>
    {% if is_paginated %}
      {% include "components/page-pagination.html" with page_obj=page_obj %}
    {% endif %}
  </div>
{% endblock %}

derrida/books/templates/books/multi_search.html
{% extends 'base.html' %}
{% load static humanize%}

{% block page-subtitle %}Search ‖ {% endblock %}
{% block nav-title %} Derrida's Library {% endblock %}

{% block header_class %}mdl-layout__header--transparent{% endblock %}

{% block page-context-id %}search-results{% endblock %}

{% block search-form-classes %}{% endblock %}

{% block content %}
<header class="page-header">
  <div class="container page-header__container">
    <h1 class="page-header__heading">Search Results</h1>
  </div>
</header>

<div class="container">
  <article class="collection collection--no-images">
    <header class="collection__header">
      <h2 class="collection__title">
        <a href="{% url 'books:list' %}?query={{ query }}">Library Books {% if instance_count %}<span class="arrow_icon">→</span><span>View {{ instance_count|intcomma }} Result{{ instance_count|pluralize }}</span>{% endif %}</a>
      </h2>
    </header>
    {% for book in instance_list %}
      {% url 'books:detail' book.slug as instance_url %}
      {% include 'components/books-list-item.html' with href=instance_url shorten=True %}
    {% empty %}
      {% include 'components/search-results-empty.html' %}
    {% endfor %}
  </article>

  <article class="collection collection--no-images">
    <header class="collection__header">
      <h2 class="collection__title">
        <a href="{% url 'books:reference-list' %}?query={{ query }}">References {% if reference_count %}<span class="arrow_icon">→</span><span>View {{ reference_count|intcomma }} Result{{ reference_count|pluralize }}</span>{% endif %}</a>
      </h2>
    </header>

    {% for reference in reference_list %}
      {% include 'components/citation-list-item.html' with reference=reference %}
    {% empty %}
      {% include 'components/search-results-empty.html' %}
    {% endfor %}
  </article>

  <article class="collection collection--no-images">
    <header class="collection__header">
      <h2 class="collection__title">
      <a href="{% url 'interventions:list' %}?query={{ query }}">Interventions {% if intervention_count %}<span class="arrow_icon">→</span>
        <span>View {{ intervention_count|intcomma }} Result{{ intervention_count|pluralize }}</span>{% endif %}</a>
    </h2>
    </header>
    {% for intervention in intervention_list %}
      {% include 'components/intervention-list-item.html' %}
    {% empty %}
      {% include 'components/search-results-empty.html' %}
    {% endfor %}
  </article>

  <article class="collection collection--no-images">
    <header class="collection__header">
      <h2 class="collection__title">
        <a href="{% url 'outwork:list' %}?query={{ query }}">Outworks {% if outwork_count %}<span class="arrow_icon">→</span>
          <span>View {{ outwork_count|intcomma }} Result{{ outwork_count|pluralize }}</span>{% endif %}</a>
      </h2>
    </header>
    {% for outwork in outwork_list %}
      {% include 'outwork/components/outwork-list-item.html' %}
    {% empty %}
      {% include 'components/search-results-empty.html' %}
    {% endfor %}
  </article>
</div>
{% endblock %}

derrida/books/templates/books/reference_detail.html
{% extends 'base.html' %}
{% load static %}

{% block page-subtitle %}{{ reference.reference_type }} from {{ reference.derridawork.short_title }}, {{ reference.derridawork_page }} ‖ {% endblock %}

{% block page-context-id %}citations-detail{% endblock %}

{% block content %}
  <header class="page-header page-header--link">
    <div class="container">
      <h1 class="page-header__heading"><a class="page-header__link" href="{% url 'books:reference-list' %}"><span class="arrow_icon">⟵</span> References</a></h1>
    </div>
  </header>
  <article class="item">
    <div class="container">
      <article class="collection">
      {% include 'components/citation-list-item.html' with book=instance %}
  </article>
    </div>
  </article>
{% endblock %}

derrida/books/templates/books/search.html
{% extends 'djiffy/base.html' %}
{% load static %}

{% block page-subtitle %}Search ‖ {% endblock %}
{% block nav-title %} Derrida's Library {% endblock %}

{% block header_class %}mdl-layout__header--transparent{% endblock %}

{% block page-context-id %}search-results{% endblock %}

{% block search-form-classes %}{% endblock %}

{% block content %}
<header class="page-header">
  <div class="container page-header__container">
    <h1 class="page-header__heading">Search Results</h1>
  </div>
</header>

<div class="container">
  <article class="collection collection--no-images">
    <header class="collection__header">
      <h2 class="collection__title">
        <a href="{% url 'books:list' %}?query={{ query }}">Library Books {% if instance_count %}<span class="arrow_icon">→</span><span>View {{ instance_count }} Result{{ instance_count|pluralize }}</span>{% endif %}</a>
      </h2>
    </header>
    {% for book in instance_list %}
      {% include 'components/books-list-item.html' %}
      {% empty %}
      <p>No trace of what you were searching for was found. Try a different keyword.</p>
    {% endfor %}
  </article>

  <article class="collection collection--no-images">
    <header class="collection__header">
      <h2 class="collection__title">
        <a href="{% url 'books:reference-list' %}">References {% if reference_count %}<span class="arrow_icon">→</span><span>View {{ reference_count }} Result{{ reference_count|pluralize }}</span>{% endif %}</a>
      </h2>
    </header>

    {% for reference in reference_list %}
      {% include 'components/citation-list-item.html' with reference=reference %}
      {% empty %}
      <p>No trace of what you were searching for was found. Try a different keyword.</p>
    {% endfor %}
  </article>

  <article class="collection collection--no-images">
    <header class="collection__header">
      <h2 class="collection__title">
      <a href="{% url 'interventions:list' %}?query={{ query }}">Annotations <span class="=arrow_icon">→</span>
        <span>View {{ intervention_count }} Result{{ intervention_count|pluralize }}</span></a>
    </h2>
    </header>
    {% for intervention in intervention_list %}
        {% include 'components/intervention-list-item.html' %}
    {% empty %}
      <p>No trace of what you were searching for was found. Try a different keyword.</p>
    {% endfor %}
  </article>

  <article class="collection collection--no-images">
    <header class="collection__header">
      <h2 class="collection__title">
        <a href="#">Outworks <span>→</span><span>View All</span></a>
      </h2>
    </header>

    {% include 'components/collection-item.html' with href='books:list' img='img/bookimg/cover1.png' itemType='outwork' %}

    {% include 'components/collection-item.html' with href='books:list' img='img/bookimg/cover2.png' itemType='outwork' %}

    {% include 'components/collection-item.html' with href='books:list' img='img/bookimg/cover3.png' itemType='outwork' %}

  </article>
</div>
{% endblock %}