derrida/books/urls.py
from django.conf.urls import url, include
from django.contrib.admin.views.decorators import staff_member_required

from derrida.books import views


app_name = 'derrida.books'

urlpatterns = [
    url(r'^publishers/autocomplete/$', staff_member_required(views.PublisherAutocomplete.as_view()),
        name='publisher-autocomplete'),
    url(r'^languages/autocomplete/$', staff_member_required(views.LanguageAutocomplete.as_view()),
        name='language-autocomplete'),

    # cross-item search
    url(r'^search/$', views.SearchView.as_view(), name='search'),

    # reference views
    url(r'^references/', include([
        url(r'^$', views.ReferenceListView.as_view(), name='reference-list'),
        url(r'^histogram/$', views.ReferenceHistogramView.as_view(),
            name='reference-histogram'),
        url(r'^histogram/(?P<derridawork_slug>[a-z-\d]+)/$',
            views.ReferenceHistogramView.as_view(), {'mode': 'section'},
            name='reference-histogram'),
        url(r'^(?P<derridawork_slug>[a-z-]+)/(?P<page>[\dA-Z]+)(?P<pageloc>[a-z]+)?/$',
            views.ReferenceDetailView.as_view(), name='reference'),
    ])),

    # library views
    url(r'^library/', include([
        url(r'^$', views.InstanceListView.as_view(), name='list'),
        url(r'^(?P<slug>[-\w]+)/', include([
            url(r'^$', views.InstanceDetailView.as_view(), name='detail'),
            url(r'^references/$',
                views.InstanceReferenceDetailView.as_view(), name='detail-references'),
            url(r'^gallery/$',
                views.InstanceDetailView.as_view(template_name='books/detail/gallery.html'),
                name='detail-gallery'),
            url(r'^gallery/(?P<short_id>[a-z0-9-]+)/$',
                views.CanvasDetail.as_view(), name='canvas-detail'),
            url(r'^suppress-images/$', views.CanvasSuppress.as_view(), name='suppress-canvas'),
            # canvas image views
            url(r'^gallery/images/(?P<page_num>[0-9vix]{1,4})-?[0-9]*[a-z]?(?P<x>@2x)?/$',
                views.CanvasImageByPageNumber.as_view(), {'mode': 'by-page'}, name='canvas-by-page'),
            url(r'^gallery/images/(?P<short_id>[a-z0-9-]+|default)/(?P<mode>smthumb|thumbnail|large|info)(?P<x>@2x)?/$',
                views.CanvasImage.as_view(), name='canvas-image'),
            url(r'^gallery/images/(?P<short_id>[a-z0-9-]+)/(?P<mode>iiif)(?P<url>.*)$',
                views.CanvasImage.as_view(), name='canvas-iiif'),

            # default thumbnail for a book
            url(r'^(?P<mode>smthumb|thumbnail)(?P<x>@2x)?/$',
                views.CanvasImage.as_view(), name='book-image')
        ])) # end library/<slug> urls
    ])), # end library urls

    url(r'^titles/(?P<pk>\d+)/', views.InstanceURIView.as_view(), name='instance'),

]

derrida/interventions/urls.py
from django.conf.urls import url
from django.contrib.admin.views.decorators import staff_member_required

from derrida.interventions import views
from derrida.interventions.models import Intervention


app_name = 'derrida.interventions'

urlpatterns = [
    url(r'^$', views.InterventionListView.as_view(), name='list'),
    url(r'^tags/autocomplete/$',
        staff_member_required(views.TagAutocomplete.as_view()), name='tag-autocomplete'),
    url(r'^tags/(?P<mode>(annotation|insertion))/autocomplete/$',
        staff_member_required(views.TagAutocomplete.as_view()), name='tag-autocomplete'),
    url(r'^autocomplete/$',
        views.InterventionAutocomplete.as_view(), name='autocomplete'),
    url(r'^(?P<id>%s)/$' % Intervention.UUID_REGEX,
        views.InterventionView.as_view(), name='view'),
]

derrida/people/urls.py
from django.conf.urls import url
from django.contrib.admin.views.decorators import staff_member_required

from derrida.people.views import PersonAutocomplete


app_name = 'derrida.people'

urlpatterns = [
    url(r'^autocomplete/person/$', staff_member_required(PersonAutocomplete.as_view()),
        name='person-autocomplete'),
]

derrida/urls.py
"""derrida URL Configuration
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
"""
from annotator_store import views as annotator_views
# from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps import views as sitemap_views
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
import mezzanine.urls
import mezzanine.pages.views

from derrida.books.views import SearchView
from derrida.books import sitemaps as book_sitemaps
from derrida.outwork import sitemaps as page_sitemaps


sitemaps = {
    'pages': page_sitemaps.PageSitemap,
    'books': book_sitemaps.InstanceSitemap,
    'book-references': book_sitemaps.InstanceReferencesSitemap,
    'book-gallery': book_sitemaps.InstanceGallerySitemap,
    'book-pages': book_sitemaps.CanvasSitemap,
}


urlpatterns = [
    # direct 500 access for testing and web scraping
    url(r"^_500/", lambda _: 1 / 0),

    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt',
        content_type='text/plain')),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico',
        permanent=True)),
    url(r'^sitemap\.xml$', sitemap_views.index, {'sitemaps': sitemaps},
        name='sitemap-index'),
    url(r'^sitemap-(?P<section>.+)\.xml$',
        sitemap_views.sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),

    # home page managed via mezzanine, but needs a named url
    url(r'^$', mezzanine.pages.views.page, {"slug": "/"}, name="home"),
    # alternate homepage named url needed for djiffy templates
    url(r'^$', mezzanine.pages.views.page, {"slug": "/"}, name="site-index"),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('pucas.cas_urls')),
    url(r'^', include('derrida.books.urls', namespace='books')),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^people/', include('derrida.people.urls', namespace='people')),
    url(r'^places/', include('derrida.places.urls', namespace='places')),
    url(r'^interventions/', include('derrida.interventions.urls',
        namespace='interventions')),
    url(r'^viaf/', include(('viapy.urls', 'viapy'), namespace='viaf')),
    url(r'^outwork/', include('derrida.outwork.urls', namespace='outwork')),

    # local version of djiffy urls
    url(r'^admin/iiif-books/',
        include(('derrida.interventions.iiif_urls', 'djiffy'),
                namespace='djiffy')),

    # annotations API
    url(r'^annotations/api/', include('annotator_store.urls',
        namespace='annotation-api')),
    # annotatorjs doesn't handle trailing slash in api prefix url
    url(r'^annotations/api', annotator_views.AnnotationIndex.as_view(),
        name='annotation-api-prefix'),

    # content pages managed by mezzanine
    url("^", include(mezzanine.urls)),
]


# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

templates/snippets/analytics.html
{% if INCLUDE_ANALYTICS%}
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-87887700-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  // anonymize IPs during configuration
  gtag('config', 'UA-87887700-3', { 'anonymize_ip': true});
</script>
{% endif %}

templates/snippets/annotator_init.html
{% load static %}
  {# include jquery-ui for autocomplete #}
  <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'js/jquery-ui.min.css' %}"/>

  {# local copy of annotator; currently v2.0.0-alpha.2 #}
  <!-- <script type="text/javascript" src="{% static 'ext/annotator/annotator.min.js' %}"></script> -->
  <script type="text/javascript" src="{% static 'js/annotator/annotator.js' %}"></script>

  <link rel="stylesheet" type="text/css" href="//emory-lits-labs.github.io/annotator-marginalia/build/0.4.0/annotator.marginalia.min.css" />
  <script type="text/javascript" src="//emory-lits-labs.github.io/annotator-marginalia/build/0.4.0/annotator.marginalia.min.js"></script>
 {# <script type="text/javascript" src="//emory-lits-labs.github.io/annotator-meltdown/build/0.3.0/annotator.meltdown.min.js"></script> #}
{# <script type="text/javascript" src="//emory-lits-labs.github.io/annotator-meltdown-zotero/build/0.1.0/annotator.meltdown.zotero.min.js"></script> <!-- includes for jquery-ui autocomplete --> #}

<!--   <script type="text/javascript" src="{% static 'js/annotator/annotator.permissions.js' %}"></script> -->

  {# // <script type="text/javascript" src="{% static 'js/annotator/tag-lookup.js' %}"></script> #}
  <link rel="stylesheet" type="text/css" href="//emory-lits-labs.github.io/annotator-imgselect/src/jquery.imgareaselect-0.9.10/css/imgareaselect-default.css" />
  <script type="text/javascript" src="{% static 'js/annotator/imgAreaSelect.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/annotator/imgselect.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/annotator/interventions-plugin.js' %}"></script>

  <link rel="stylesheet" type="text/css" href="{% static 'ext/annotator/annotator.min.css' %}"/>
  {# <link rel="stylesheet" type="text/css" href="//emory-lits-labs.github.io/annotator-meltdown/build/0.3.0/annotator.meltdown.min.css" /> #}
   <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

  {# Include local style overrides for the annotator in Winthrop #}
  <link rel='stylesheet' type='text/css' href='{% static "css/derrida-annotator.css" %}' />


{# Initialize annotator.js *#}
<script type="text/javascript" charset="utf-8">


/** Django CSRF token handling for ajax put/post/delete requests.
Based on https://docs.djangoproject.com/en/1.11/ref/csrf/#ajax
*/
// NOTE: could use jquery cookie plugin instead of this method
// http://plugins.jquery.com/cookie/
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
var csrftoken = getCookie('csrftoken');

function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            // Send the token to same-origin, relative URLs only.
            // Send the token only if the method warrants CSRF protection
            // Using the CSRFToken value acquired earlier
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});


   $(function () {
    // Use canvas URI to associate new annotations and load
    // existing ones.
    var content_uri = "{{ canvas.uri }}";

    var contentUri = function () {
        return {
            beforeAnnotationCreated: function (annotation) {
                annotation.uri = content_uri;
            }
        };
    };

  var autocomplete_url = {
    language: "{% url 'books:language-autocomplete' %}",
    annotator: "{% url 'people:person-autocomplete' %}",
{#    subject:  "{% url 'books:subject-autocomplete' %}", #}
// NOTE: in future, mode will need to be set based on intervention type
    tag: "{% url 'interventions:tag-autocomplete' mode='annotation' %}"
  };

var language_choices = {{ languages_js|safe }};
var fields = [
    {
      name: 'author',
      label: 'Author',
      default: {{ default_intervener|safe }},
      autocompleteURL: autocomplete_url.annotator
    },
    {
      name: 'text_language',
      label: 'Language',
      type: 'select',
      choices: language_choices
      // NOTE: could also use choicesURL to load choices, e.g.
      // choicesURL: autocomplete_url.language
    },
    {
      name: 'text_translation',
      label: 'Translation',
      type: 'textarea',
      placeholder: 'Translation of annotation text (optional)'
    },
    {
      name: 'quote',
      label: 'Anchor Text',
      type: 'textarea'
    },
    {
      name: 'quote_language',
      label: 'Anchor Text Language',
      type: 'select',
      choices: language_choices
    },
    {
      name: 'tags',
      label: 'Tags',
      list: true,
      autocompleteURL: autocomplete_url.tag
    }
  {% comment %}
/*    { name: 'translation',
      label: 'Translation',
      size: 'textarea'
    },
    {
      name: 'subjects',
      label: 'Subjects',
      placeholder: 'Type or click to select subjects',
      list: true,
      autocompleteUrl: autocomplete_url.subject
    },
    {
      name: 'author',
      label: 'Annotator',
      placeholder: 'Type or click to select annotator',
      autocompleteUrl: autocomplete_url.annotator
    },
    {
      name: 'quote',
      label: 'Anchor text',
      size: 'textarea'
    },
    {
      name: 'anchor_translation',
      label: 'Anchor text translation',
      size: 'textarea'
    },
    }*/  {% endcomment %}
  ];

  var interventions = annotatorInterventions(fields);

  var marginalia_opts = {
    show_author: true,
     viewer: interventions.viewer,
    renderExtensions: [
        // annotation_permissions.renderExtension,
        interventions.renderExtension,
    ],
    toggle: {
      class: 'btn btn-green',
      show: function(){
        $(".carousel-control").fadeOut();
      },
      hide: function(){
        $(".carousel-control").fadeIn();
      }
    }
  };


  // configuring marginalia here so it can be referenced in annotator search
  var _marginalia = annotatorMarginalia(marginalia_opts);

/* custom authz policy based on current django user permissions
  NOTE: django permissions are enforced by the api, but this allows
  marginalia to only display edit and delete options based on what
  the user should be able to do.
*/
var user_permissions = {
  update: {{ perms.annotator_store.change_annotation|lower }},
  delete: {{ perms.annotator_store.delete_annotation|lower }},
}
annotator.authz.AclAuthzPolicy.prototype.permits = function (action, context, identity) {
  return user_permissions[action];
}

  var app = new annotator.App()
      .include(contentUri)
      .include(annotator.ui.main, {
          element: document.querySelector('.content .inner'),
          {% comment %}/*  {# not using default viewer, so these don't matter, see marginalia #}
          viewerExtensions: [
              annotatormeltdown.viewerExtension,
              annotator.ui.tags.viewerExtension
          ],
          */
          {% endcomment %}
          editorExtensions: [
            interventions.editorExtension,
          ]
      })
      .include(annotatorImageSelect, {
        element: $('.content .inner img'),
      })
      .include(annotator.storage.http, {
          prefix: '{% url "annotation-api-prefix" %}',
          headers: {"X-CSRFToken": csrftoken}
      })
      .include(annotatorMarginalia, marginalia_opts)

  app.start()
      .then(function () {
          // {# {% if mode = 'full' %} #}
           app.annotations.load({uri: content_uri});
          //{#  {% endif %} #}
      });
  {# set user identity to allow for basic permission checking #}
  app.ident.identity = "{{ user.username }}";
  // set superuser status to allow auth checking
  // (enforced at application level, only affects what is displayed)
  app.ident.is_superuser = {{ request.user.is_superuser|lower }}

});
</script>

templates/snippets/local_styles.html
{% load static compress %}


{# Counter will need to be re-enabled for font css in production #}
{% compress css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/MyFontsWebfontsKit.css' %}">
{% endcompress %}
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="{% static "css/material.min.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/webui-popover.min.css" %}" />
{% compress css %}
<link rel="stylesheet" type="text/x-scss" href="{% static "scss/style.scss" %}" />
{% endcompress %}

templates/snippets/test_banner.html
{% if SHOW_TEST_WARNING %}
<div class="ribbon-box fade">
  <div class="ribbon-wrapper">
    <div class="ribbon"><h2>This is a <b>TEST</b> site</h2>
    <p>Content may change or be removed without warning</p>
    <button>OK</button>
    </div>
  </div>
</div>
{% endif %}