derrida/books/urls.py
from django.conf.urls import url, include
from django.contrib.admin.views.decorators import staff_member_required

from derrida.books import views


app_name = 'derrida.books'

urlpatterns = [
    url(r'^publishers/autocomplete/$', staff_member_required(views.PublisherAutocomplete.as_view()),
        name='publisher-autocomplete'),
    url(r'^languages/autocomplete/$', staff_member_required(views.LanguageAutocomplete.as_view()),
        name='language-autocomplete'),

    # cross-item search
    url(r'^search/$', views.SearchView.as_view(), name='search'),

    # reference views
    url(r'^references/', include([
        url(r'^$', views.ReferenceListView.as_view(), name='reference-list'),
        url(r'^histogram/$', views.ReferenceHistogramView.as_view(),
            name='reference-histogram'),
        url(r'^histogram/(?P<derridawork_slug>[a-z-\d]+)/$',
            views.ReferenceHistogramView.as_view(), {'mode': 'section'},
            name='reference-histogram'),
        url(r'^(?P<derridawork_slug>[a-z-]+)/(?P<page>[\dA-Z]+)(?P<pageloc>[a-z]+)?/$',
            views.ReferenceDetailView.as_view(), name='reference'),
    ])),

    # library views
    url(r'^library/', include([
        url(r'^$', views.InstanceListView.as_view(), name='list'),
        url(r'^(?P<slug>[-\w]+)/', include([
            url(r'^$', views.InstanceDetailView.as_view(), name='detail'),
            url(r'^references/$',
                views.InstanceReferenceDetailView.as_view(), name='detail-references'),
            url(r'^gallery/$',
                views.InstanceDetailView.as_view(template_name='books/detail/gallery.html'),
                name='detail-gallery'),
            url(r'^gallery/(?P<short_id>[a-z0-9-]+)/$',
                views.CanvasDetail.as_view(), name='canvas-detail'),
            url(r'^suppress-images/$', views.CanvasSuppress.as_view(), name='suppress-canvas'),
            # canvas image views
            url(r'^gallery/images/(?P<page_num>[0-9vix]{1,4})-?[0-9]*[a-z]?(?P<x>@2x)?/$',
                views.CanvasImageByPageNumber.as_view(), {'mode': 'by-page'}, name='canvas-by-page'),
            url(r'^gallery/images/(?P<short_id>[a-z0-9-]+|default)/(?P<mode>smthumb|thumbnail|large|info)(?P<x>@2x)?/$',
                views.CanvasImage.as_view(), name='canvas-image'),
            url(r'^gallery/images/(?P<short_id>[a-z0-9-]+)/(?P<mode>iiif)(?P<url>.*)$',
                views.CanvasImage.as_view(), name='canvas-iiif'),

            # default thumbnail for a book
            url(r'^(?P<mode>smthumb|thumbnail)(?P<x>@2x)?/$',
                views.CanvasImage.as_view(), name='book-image')
        ])) # end library/<slug> urls
    ])), # end library urls

    url(r'^titles/(?P<pk>\d+)/', views.InstanceURIView.as_view(), name='instance'),

]

derrida/urls.py
"""derrida URL Configuration
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
"""
from annotator_store import views as annotator_views
# from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps import views as sitemap_views
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
import mezzanine.urls
import mezzanine.pages.views

from derrida.books.views import SearchView
from derrida.books import sitemaps as book_sitemaps
from derrida.outwork import sitemaps as page_sitemaps


sitemaps = {
    'pages': page_sitemaps.PageSitemap,
    'books': book_sitemaps.InstanceSitemap,
    'book-references': book_sitemaps.InstanceReferencesSitemap,
    'book-gallery': book_sitemaps.InstanceGallerySitemap,
    'book-pages': book_sitemaps.CanvasSitemap,
}


urlpatterns = [
    # direct 500 access for testing and web scraping
    url(r"^_500/", lambda _: 1 / 0),

    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt',
        content_type='text/plain')),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico',
        permanent=True)),
    url(r'^sitemap\.xml$', sitemap_views.index, {'sitemaps': sitemaps},
        name='sitemap-index'),
    url(r'^sitemap-(?P<section>.+)\.xml$',
        sitemap_views.sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),

    # home page managed via mezzanine, but needs a named url
    url(r'^$', mezzanine.pages.views.page, {"slug": "/"}, name="home"),
    # alternate homepage named url needed for djiffy templates
    url(r'^$', mezzanine.pages.views.page, {"slug": "/"}, name="site-index"),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('pucas.cas_urls')),
    url(r'^', include('derrida.books.urls', namespace='books')),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^people/', include('derrida.people.urls', namespace='people')),
    url(r'^places/', include('derrida.places.urls', namespace='places')),
    url(r'^interventions/', include('derrida.interventions.urls',
        namespace='interventions')),
    url(r'^viaf/', include(('viapy.urls', 'viapy'), namespace='viaf')),
    url(r'^outwork/', include('derrida.outwork.urls', namespace='outwork')),

    # local version of djiffy urls
    url(r'^admin/iiif-books/',
        include(('derrida.interventions.iiif_urls', 'djiffy'),
                namespace='djiffy')),

    # annotations API
    url(r'^annotations/api/', include('annotator_store.urls',
        namespace='annotation-api')),
    # annotatorjs doesn't handle trailing slash in api prefix url
    url(r'^annotations/api', annotator_views.AnnotationIndex.as_view(),
        name='annotation-api-prefix'),

    # content pages managed by mezzanine
    url("^", include(mezzanine.urls)),
]


# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

templates/components/collection-item.html
{% load static %}

<section class="collection__item item {{itemType}}">
  <figure class="item__image">
    {% if href %}
    <a class="item__image-link" href="{% url href %}">
    {% endif %}
      {% if img %}
      <img class="img" src="{% static img %}" />
      {% else %}
      <span class="img img--placeholder"></span>
      {% endif %}
    {% if href %}
    </a>
    {% endif %}
  </figure>
  <div class="item__body">
    {% if itemType == 'annotation' %}
    <a class="text-badge text-badge--red text-badge--link" href="#">Annotation</a>
    {% else %}
    <a class="text-badge text-badge--blue text-badge--link" href="#">Reference</a>
    {% endif%}
    <h3 class="item__heading"><a class="item__link" href="#">Cours de linguistique générale</a></h3>
    <p class="item__author">Ferdinand de Saussure</p>
    <p class="item__date">1931</p>
    <p class="item__location">pp 169-280</p>
    <p class="item__excerpt">Je ne sais comment cela se fait, mais je sais bien que les opérations dont on tient le plus de registres et de livres de compte sont précisément celles où l’on friponne le plus.</p>
    <p class="item__citation">Cited in De la grammatologie  p. 401</p>
  </div>
</section>

templates/components/footer.html
{% load static pages_tags i18n %}

<footer class="mdl-mega-footer">

  <div class="grid-container">
    <div class="mdl-mega-footer__middle-section">

      <div class="mdl-mega-footer-section" id="derrida-footer">
         {% for page in page_branch %}
            {% if page.in_menu %}
              {# break for second section on first occurence of primary menu item #}
              {% if '1' in page.in_menus %}{% ifchanged %}
                </div>
                 <div class="mdl-mega-footer-section">
              {% endifchanged %}{% endif %}
              {% with page.get_absolute_url as url %}
              <a class="mdl-mega-footer__heading" href="{{ url }}">{% if url == '/' %}Home{% else %}{{ page.title }}{% endif %}</a>
              {% endwith %}
            {% endif %}
          {% endfor %}
      </div>

      <div class="mdl-mega-footer-section mdl-mega-footer__branding-section">
        <div class="mdl-mega-footer__logos">
          <a href="{% url 'home' %}" title="Derrida's Margins Home"><img class="logo" width="150" src="{% static "img/derrida_VI_logo_full.svg" %}" alt="Derrida's Margins"/></a>
          <a href="https://cdh.princeton.edu" title="CDH @ Princeton"><img class="logo" height="70" src="{% static "img/CDH_logo_01.svg" %}" alt="The Center for Digital Humanities @ Princeton"/></a>
          <a href="https://www.princeton.edu" title="Princeton University"><img class="logo" height="80" src="{% static "img/PU_logo_web_XL.svg" %}" alt="Princeton University"/></a>

        </div>
      </div>
    </div>

    <div class="mdl-mega-footer__bottom-section">
      <p id="sw_version">{{ SW_VERSION }}</p>
      <p>©2021 Trustees of Princeton University
        <a href="https://accessibility.princeton.edu/accessibility-assistance">Accessibility Assistance</a>
      </p>
      {% block footer-content %}{% endblock %}
    </div>
  </div>
</footer>

templates/components/item-navigation-tabs.html
<nav class="item-nav">
  <a href="{% url 'bibliography' %}" class="item-nav__link {% if is_biblio %}item-nav__link--active{% endif %}">Bibliography</a>
  <span class="item-nav__spacer"></span>
  <a href="{% url 'image-gallery' %}" class="item-nav__link {% if is_gallery %}item-nav__link--active{% endif %}">Image Gallery</a>
  <span class="item-nav__spacer"></span>
  <a href="{% url 'citation-view' %}" class="item-nav__link {% if is_citation %}item-nav__link--active{% endif %}">Citation View</a>
  <span class="item-nav__spacer item-nav__spacer--end"></span>
</nav>

templates/components/navlinks.html
{% load pages_tags i18n %}
{# primary site navigation #}
{% for page in page_branch %}
    {% if page.in_menu %}
    <a class="mdl-navigation__link {% if page.is_current_or_ascendant %}mdl-navigation__link--active{% endif %}" href="{{ page.get_absolute_url }}">
      <span class="navigation-title">{{ page.title }}</span>
    </a>
    {% endif %}
{% endfor %}

templates/components/page-filter.html
{% load static widget_tweaks %}
{% include 'components/search-form-header-init.html' %}
<section class="page-filter {% if not hide_filter %}is-visible{% endif %}">

<form class="page-filter__form">
  <p class='sr-only'>Use escape to immediately leave any filter panel</p>

  <div class="container">
    <header class="page-filter__header">
      <p class="toggle-text"></p>
    </header>
    <section class="filter__section filter__section--toggles">

      {% if 'is_extant' in form.fields %}
      <div class="filter__selector"> {# is_extant #}
        <label class="mdl-switch__label mdl-switch__label--right" for="is-extant">{{ form.is_extant.label }}
          <span class="mdl-switch mdl-switch--right mdl-js-switch">
            {% render_field form.is_extant class="mdl-switch__input" id="is-extant" %}
          </span>
        </label>
      </div>
      {% endif %}

      {% if 'is_annotated' in form.fields %}
      <div class="filter__selector">  {# is_annotated #}
        <label class="mdl-switch__label mdl-switch__label--right" for="is-annotation">{{ form.is_annotated.label }}
          <span class="mdl-switch mdl-switch--right mdl-js-switch">
            {% render_field form.is_annotated class="mdl-switch__input" id="is-annotation" %}
          </span>
        </label>
      </div>
      {% endif %}

      {# FIXME: reusing id because otherwise javascript doesn't fire, but not sure where set #}
      {% if 'corresponding_intervention' in form.fields %}
      <div class="filter__selector">
        <label class="mdl-switch__label mdl-switch__label--right" for="corresponding_intervention">{{ form.corresponding_intervention.label }}
          <span class="mdl-switch mdl-switch--right mdl-js-switch">
            {% render_field form.corresponding_intervention class="mdl-switch__input" id="corresponding_intervention" %}
          </span>
        </label>
      </div>
      {% endif %}
    </section>

    <section class="filter__section">
      {% if 'author' in form.fields %}
      <div class="filter__selector">
        {% include 'components/form/author-selection.html' with authors=form.author %}
      </div>
      {% endif %}

      {% if 'subject' in form.fields %}
      <div class="filter__selector">
        {% include 'components/form/checkbox-selection.html' with name='subject' label=form.subject.label items=form.subject %}
      </div>
      {% endif %}

      {% if 'derridawork' in form.fields %}
      <div class="filter__selector filter__selector--condensed">
        {% include 'components/form/checkbox-selection.html' with disabled='disabled' name='derridawork' label=form.derridawork.label items=form.derridawork %}
      </div>
      {% endif %}

      {% if 'language' in form.fields %}
      <div class="filter__selector filter__selector--condensed">
        {% include 'components/form/checkbox-selection.html' with name='language' label=form.language.label items=form.language %}
      </div>
      {% endif %}

      {% if 'work_language' in form.fields %}
      <div class="filter__selector filter__selector--condensed">
        {% include 'components/form/checkbox-selection.html' with name='work_language' label=form.work_language.label items=form.work_language %}
      </div>
      {% endif %}

      {% if 'original_language' in form.fields %}
      <div class="filter__selector filter__selector--condensed">
        {% include 'components/form/checkbox-selection.html' with name='original_language' label=form.original_language.label items=form.original_language %}
      </div>
      {% endif %}

      {% if 'pub_place' in form.fields %}
      <div class="filter__selector filter__selector--condensed">
        {% include 'components/form/checkbox-selection.html' with name='pub_place' label=form.pub_place.label items=form.pub_place %}
      </div>
      {% endif %}

      {% if 'annotation_language' in form.fields %}
      <div class="filter__selector filter__selector--condensed">
        {% include 'components/form/checkbox-selection.html' with name='annotation_language' label=form.annotation_language.label items=form.annotation_language %}
      </div>
      {% endif %}

      {% if 'annotation_type' in form.fields %}
      <div class="filter__selector filter__selector--condensed">
        {% include 'components/form/checkbox-selection.html' with name='annotation_type' label=form.annotation_type.label items=form.annotation_type %}
      </div>
      {% endif %}

      {% if 'hand' in form.fields %}
      <div class="filter__selector filter__selector--condensed">
        {% include 'components/form/checkbox-selection.html' with name='hand' label=form.hand.label items=form.hand %}
      </div>
      {% endif %}

      {% if 'ink' in form.fields %}
      <div class="filter__selector filter__selector--condensed">
        {% include 'components/form/checkbox-selection.html' with name='ink' label=form.ink.label items=form.ink %}
      </div>
      {% endif %}

      {% if 'item_type' in form.fields %}
      <div class="filter__selector filter__selector--condensed">
        {% include 'components/form/checkbox-selection.html' with name='publication_type' label=form.item_type.label items=form.item_type %}
      </div>
      {% endif %}

      {% if 'reference_type' in form.fields %}
      <div class="filter__selector filter__selector--condensed">
        {% include 'components/form/checkbox-selection.html' with name='reference_type' label=form.reference_type.label items=form.reference_type %}
      </div>
      {% endif %}

      {% if 'cited_in' in form.fields %}
      <div class="filter__selector filter__selector--condensed">
        {% include 'components/form/checkbox-selection.html' with name='cited_in' label=form.cited_in.label items=form.cited_in %}
      </div>
      {% endif %}

      {% if form.work_year %}
      <div class="filter__selector filter__selector--condensed">
        {% include 'components/form/year-selection.html' with name='work_year' label=form.work_year.label items=form.work_year ranges=facets.ranges.work_year %}
      </div>
      {% endif %}

      {% if form.copyright_year %}
      <div class="filter__selector filter__selector--condensed">
        {% include 'components/form/year-selection.html' with name='copyright_year' label=form.copyright_year.label items=form.copyright_year ranges=facets.ranges.copyright_year %}
      </div>
      {% endif %}

      {% if form.print_year %}
      <div class="filter__selector filter__selector--condensed">
        {% include 'components/form/year-selection.html' with name='print_year' label=form.print_year.label items=form.print_year ranges=facets.ranges.print_year %}
      </div>
      {% endif %}

      {% if form.instance_work_year %}
      <div class="filter__selector filter__selector--condensed">
        {% include 'components/form/year-selection.html' with name='instance_work_year' label=form.instance_work_year.label items=form.instance_work_year ranges=facets.ranges.instance_work_year %}
      </div>
      {% endif %}

      {% if form.instance_copyright_year %}
      <div class="filter__selector filter__selector--condensed">
        {% include 'components/form/year-selection.html' with name='instance_copyright_year' label=form.instance_copyright_year.label items=form.instance_copyright_year ranges=facets.ranges.instance_copyright_year %}
      </div>
      {% endif %}

      {% if form.instance_print_year %}
      <div class="filter__selector filter__selector--condensed">
        {% include 'components/form/year-selection.html' with name='instance_print_year' label=form.instance_print_year.label items=form.instance_print_year ranges=facets.ranges.instance_print_year %}
      </div>
      {% endif %}

      {% if form.item_work_year %}
      <div class="filter__selector filter__selector--condensed">
        {% include 'components/form/year-selection.html' with name='item_work_year' label=form.item_work_year.label items=form.item_work_year ranges=facets.ranges.item_work_year %}
      </div>
      {% endif %}

      {% if form.item_copyright_year %}
      <div class="filter__selector filter__selector--condensed">
        {% include 'components/form/year-selection.html' with name='item_copyright_year' label=form.item_copyright_year.label items=form.item_copyright_year ranges=facets.ranges.item_copyright_year %}
      </div>
      {% endif %}

      {% if form.item_print_year %}
      <div class="filter__selector filter__selector--condensed">
        {% include 'components/form/year-selection.html' with name='item_print_year' label=form.item_print_year.label items=form.item_print_year ranges=facets.ranges.item_print_year %}
      </div>
      {% endif %}

    </section>

    {# We need to update the components after being rendered in each of the checkbox-selection #}
    <script>
      $(function() {
        componentHandler.upgradeDom();
      });
    </script>
  </div>
  <input type="submit" value="submit" class="sr-only"/>
  </form>
  <footer class="page-filter__footer">
    <div class="page-filter__status-icon">
      <svg class="svg-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M8.48,3.25a2,2,0,0,0-3.55,0H2.4v2H5a2,2,0,0,0,3.34,0H17.6v-2Z" fill="#979797"/><path d="M13.4,8.25a2,2,0,0,0-1.51.7H2.4v2h9.13a2,2,0,0,0,3.73,0H17.6V9H14.91A2,2,0,0,0,13.4,8.25Z" fill="#979797"/><path d="M6.8,13.85a2,2,0,0,0-1.59.8H2.4v2H5a2,2,0,0,0,3.66,0h9v-2H8.39A2,2,0,0,0,6.8,13.85Z" fill="#979797"/></svg>
    </div>
    <button class="toggle-button">
      <i class="md-icon material-icons md-icon--hide">keyboard_arrow_down</i>
      <i class="md-icon material-icons md-icon--show">keyboard_arrow_up</i>
    </button>
  </footer>
</section>

templates/components/page-pagination.html
{% load derrida_tags %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
          <a class="pagination__nav-link" href="?{% querystring_replace page=page_obj.previous_page_number %}"><span class="arrow_icon">⟵</span></a>
        {% endif %}

        <nav class="pagination__page-links">
          {% for number in page_obj.paginator.page_range %}
            {# Make sure we get the first page #}
            {% if forloop.first and number != page_obj.number %}
              <a class="pagination__page-link" href='?{% querystring_replace page=number %}'>{{ number }}</a>
              <span class="pagination__page-link-seperator">...</span>
            {% endif %}
            {% if number != 1 and number != page_obj.paginator.num_pages and number|add:"3" >= page_obj.number and number <= page_obj.number|add:"4" and number != page_obj.number  %}
              <a class="pagination__page-link" href='?{% querystring_replace page=number %}'>{{ number }}</a>
            {% endif %}

            {% if number == page_obj.number %}
              <a class="pagination__page-link pagination__page-link--current" href='?{% querystring_replace page=number %}'>{{ number }}</a>
            {% endif %}

            {# Make sure we get the last page#}
            {% if forloop.last and number != page_obj.number %}
              <span class="pagination__page-link-seperator">...</span>
              <a class="pagination__page-link" href='?{% querystring_replace page=number %}'>{{ number}}</a>
            {% endif%}
          {% endfor %}
        </nav>

        {% if page_obj.has_next %}
          <a class="pagination__nav-link" href="?{% querystring_replace page=page_obj.next_page_number %}"><span class="arrow_icon">⟶</span></a>
        {% endif %}
    </span>
</div>

templates/components/page-sort.html
{% load humanize widget_tweaks %}
<section class="page-sort">
  <div class="container">
    <header class="page-sort__header">
      <p class="sort-label sort-label--diminished ">{{ total|intcomma }} Result{{ total|pluralize }}</p>
      <a class="sort-link" href="{{ request.path }}">Clear All</a>
    </header>
    {% if form.order_by %}
    <header class="page-sort__header">
      <p class="sort-label">Sort By</p>
      <form class="order_by">
        <fieldset>
          <legend>Sort options</legend>
        {% render_field form.order_by class="order_by__options" %}
      </fieldset>
      <input type="submit" value="submit" class="sr-only"/>
      </form>
    </header>
    {% endif %}
  </div>
</section>

templates/components/search-bar.html
{% load static widget_tweaks %}

<section class="container">
  <form class="search-form-header__form" action="{% url 'search' %}">
    <span class="mdl-button mdl-button--search mdl-js-button mdl-button--icon mdl-textfield__label--disabled">
      <img class="img" src="{% static "img/icons/Search.svg" %}" alt="Search"/>
    </span>
    <div class="mdl-textfield mdl-js-textfield">
      {% render_field search_form.query class+='mdl-textfield__input' %}
      <label class="mdl-textfield__label mdl-textfield__label--search" for="{{ search_form.query.id_for_label }}">{{ search_form.query.label }}</label>
    </div>
    <div class="mdl-selectfield mdl-js-selectfield">
     {% render_field search_form.content_type class+="mdl-selectfield__select" title=search_form.content_type.label %}
    <label class="sr-only" for="{{ search_form.content_type.id_for_label }}">{{ search_form.content_type.label }}</label>
    </div>
    <div class="mdl-button mdl-js-button mdl-button--icon" data-action="toggle-search-form">
      <svg class="svg" xmlns="http://www.w3.org/2000/svg"><polygon points="17.62 3.79 16.21 2.38 10 8.59 3.79 2.38 2.38 3.79 8.59 10 2.38 16.21 3.79 17.62 10 11.41 16.21 17.62 17.62 16.21 11.41 10 17.62 3.79" fill="#FFFFFF"/></svg>
    </div>
    <input type="submit" value="submit" class="submit-button is-hidden" />
  </form>
</section>

templates/components/search-form-header-init.html
{% if form.query or search_form.query %}
<script>
  $(function() {
    var $searchFormHeader = $(".search-form-header");
    if ($searchFormHeader.length && $searchFormHeader.find(".mdl-textfield__input").val().length) {
      $(".search-form-header").removeClass("is-hidden");
    }

    if (window.selectizedFields) {
      var searchFormSelectize = $.grep(window.selectizedFields, function(selectize){
        return "id_content_type-selectized" === window.selectizedFields[0].$control_input[0].id;
      });

      if (searchFormSelectize.length) {
        searchFormSelectize = searchFormSelectize[0];
        var path = window.location.pathname;
        if (path.indexOf("library") > 0) {
          searchFormSelectize.setValue("book");
        } else if (path.indexOf("references") > 0) {
          searchFormSelectize.setValue("reference");
        } else if (path.indexOf("interventions") > 0) {
          searchFormSelectize.setValue("intervention");
        } else if (path.indexOf("outwork") > 0) {
          searchFormSelectize.setValue("outwork");
        }
      }
    }
  });
</script>
{% endif %}

templates/components/search-results-empty.html
{% comment %}
The search-results-empty template is used to display the message whenever
a search returns an empty collection. This is used on search result pages and
on list pages when applying a filter results in an empty collection.
{% endcomment %}

<section class="search__no-results">
  <p>No trace of what you were searching for was found. Try a different keyword.</p>
</section>

templates/components/visualization-marker.html
{# single reference marker for histogram viz; expects a reference dict as returned by summary_value #}
<div class="visualization-marker-container">
{% url 'books:reference' derridawork_slug=ref.derridawork__slug page=ref.derridawork_page pageloc=ref.derridawork_pageloc  as ref_url%}
{# NOTE: omitting id attribute (formerly id="tt{{ ref.id }}" because ids are not distinct for multi-author works and id is not used #}
  <div role="button" class="visualization-chapter-marker"
     href="{% url 'books:detail' slug=ref.instance__slug %}"
     data-url="{{ ref_url }}"
     tabindex="0">
    Reference on page {{ ref.derridawork_page }}
  </div>
</div>